Create a notebook that creates simple charts
KeNing001/github-stars-pipeline pull request #8
Opened 2024-11-01 00:15 UTC by KeNing001

- Add Notebook
- Create Charts 
- Update README

2024-11-01 00:18 UTC, KeNing001 commented
Changes about the DBT Document could be ignored, it goes with last PR.

2024-11-01 21:56 UTC, edsioufi requested changes
Great progress and dropped some comments to improve the notebook!

2024-11-01 21:56 UTC, edsioufi commented on notebooks/gharchive.ipynb
Great job! A couple of notes:

1. It'd be great to save your file after running it so that we can get the charts here in Github. It might be also that you're using dynamic rendering (a setting in jupyter notebooks), in which case the charts won't show up here on github at all.

2. You don't need to export to csv and re-read the csv file. You already have the dataframe in memory from the SQL query cell :)

3. Since you now have the charts, I'd suggest adding the png to the README.md to showcase it!

2024-11-18 21:54 UTC, edsioufi approved these changes
Graphs and reamde look neat! Awesome stuff 🚀

2024-11-18 22:04 UTC, merged